version: "3.9"
services:
  app:
    build: .
    environment:
      - SECRET_KEY=change-me
      - VIRTUAL_HOST=disparos.abmix.tech
      - LETSENCRYPT_HOST=disparos.abmix.tech
      - LETSENCRYPT_EMAIL=contato@abmix.com.br
    volumes:
      - ./instance:/app/instance
    expose:
      - "5000"
    networks:
      - nginx-proxy
    restart: unless-stopped

networks:
  nginx-proxy:
    external: true
    name: stack_nginx-proxy
